var InfiniteHell=InfiniteHell||{}
InfiniteHell.Game=function(){},InfiniteHell.Game.prototype={preload:function(){this.game.time.advancedTiming=!0},init:function(t){void 0===t&&(t=0),this.anotherLives=t},create:function(){this.game.world.setBounds(0,0,3584,this.game.height),this.ground=this.add.tileSprite(0,this.game.height-88,this.game.world.width,88,"ground"),this.background=this.game.add.tileSprite(0,-48,this.game.world.width,this.game.height,"background"),this.background.alpha=.4,this.fire=[],this.fireHelp=[]
for(var t=0;29>t;t++)this.fireHelp[t]=t
for(var i=0;i<this.fireHelp.length;i++)this.fire=this.game.add.sprite(this.game.world.width-128*this.fireHelp[i],this.game.height-200,"fire"),this.fire.animations.add("burn"),this.fire.animations.play("burn",8,!0)
this.player=this.game.add.sprite(this.game.width/2,this.game.height-88,"player"),this.player.animations.add("walk"),this.generateManticores(),this.generateOrcs(),this.generateTrolls(),this.generateChests(),this.game.physics.arcade.enable(this.player),this.game.physics.arcade.enable(this.ground),this.player.body.gravity.y=900,this.ground.body.immovable=!0,this.ground.body.allowGravity=!1
var e=this.game.cache.getImage("playerGrab")
this.player.animations.add("grab"),this.player.grabDimensions={width:e.width,height:e.height}
var s=this.game.cache.getImage("playerHit")
this.player.animations.add("hit"),this.player.hitDimensions={width:s.width,height:s.height},this.player.standDimensions={width:this.player.width,height:this.player.height},this.player.anchor.setTo(.5,1),this.game.camera.follow(this.player),this.player.animations.play("walk",5,!0),this.cursors=this.game.input.keyboard.createCursorKeys(),this.swipe=this.game.input.activePointer,this.grabSound=this.game.add.audio("grab"),this.hitSound=this.game.add.audio("hit"),this.dieSound=this.game.add.audio("die"),this.scratches=0,this.points=0,this.wrapping=!0,this.stopped=!1,this.lives=6
var a=this.game.add.sprite(0,this.game.height-148,"armor"),h=this.game.add.sprite(0,this.game.height-142,"book"),r=this.game.add.sprite(0,this.game.height-142,"gold"),o=this.game.add.sprite(0,this.game.height-142,"potion"),n=this.game.add.sprite(0,this.game.height-148,"ring"),d=this.game.add.sprite(0,this.game.height-142,"scroll")
a.visible=!1,h.visible=!1,r.visible=!1,o.visible=!1,n.visible=!1,d.visible=!1,this.artifacts=[a,h,r,o,n,d],this.currentArtifact=r
var l={font:"40px Times New Roman",fill:"#FFFFFF"},g=this.game.add.text(20,30,"Score:",l),p=this.game.add.sprite(this.game.width-130,30,"lives")
g.fixedToCamera=!0,p.fixedToCamera=!0
var c={font:"40px Times New Roman",fill:"#FFFFFF"}
this.pointsText=this.game.add.text(150,30,"",c),this.livesText=this.game.add.text(this.game.width-80,30,"",c),this.refreshStats(),this.pointsText.fixedToCamera=!0,this.livesText.fixedToCamera=!0,this.game.world.bringToTop(this.background),this.game.world.bringToTop(this.fire),this.game.world.bringToTop(this.chests),this.game.world.bringToTop(this.ground)},update:function(){this.game.physics.arcade.collide(this.player,this.ground,this.playerHit,null,this),this.game.physics.arcade.collide(this.player,this.manticores,this.playerBit,null,this),this.game.physics.arcade.collide(this.player,this.orcs,this.playerBit,null,this),this.game.physics.arcade.collide(this.player,this.trolls,this.playerBit,null,this),this.game.physics.arcade.overlap(this.player,this.chests,this.collect,this.checkGrab,this),this.player.alive&&!this.stopped&&(this.player.body.velocity.x=350,!this.wrapping&&this.player.x<this.game.width?(this.chests.destroy(),this.generateChests(),this.wrapping=!0,this.manticores.destroy(),this.generateManticores(),this.orcs.destroy(),this.generateOrcs(),this.trolls.destroy(),this.generateTrolls(),this.game.world.bringToTop(this.background),this.game.world.bringToTop(this.fire),this.game.world.bringToTop(this.chests),this.game.world.bringToTop(this.ground)):this.player.x>=this.game.width&&(this.wrapping=!1),this.swipe.isDown&&this.swipe.positionDown.y>this.swipe.position.y?this.playerJump():this.cursors.up.isDown&&this.playerJump(),this.game.world.wrap(this.player,-(this.game.width/2),!1,!0,!1))},refreshStats:function(){this.pointsText.text=this.points,this.livesText.text=this.lives-this.scratches+this.anotherLives},playerBit:function(t,i){i.destroy(),this.scratches++,this.refreshStats(),this.player.loadTexture("playerHit"),this.player.animations.play("hit",10,!0),this.hitSound.play(),this.stopped=!0,this.player.body.velocity.x=0,this.game.time.events.add(2*Phaser.Timer.SECOND,this.playerScratch,this)},collect:function(t,i){this.stopped||(this.player.loadTexture("playerGrab"),this.player.animations.play("grab",10,!0),this.player.body.setSize(this.player.grabDimensions.width,this.player.grabDimensions.height),this.currentChest=i,this.stopped=!0,this.player.body.velocity.x=0,this.game.time.events.add(2*Phaser.Timer.SECOND,this.playerGrab,this))},gameOver:function(){this.game.state.start("Menu")},checkGrab:function(){return this.cursors.down.isDown||this.swipe.isDown&&this.swipe.position.y>this.swipe.positionDown.y?!0:!1},playerJump:function(){this.player.body.touching.down&&(this.player.body.velocity.y=-750)},playerGrab:function(){this.grabSound.play()
var t=this.currentChest.x
this.currentChest.destroy(),this.currentArtifact=this.artifacts[Math.floor(Math.random()*this.artifacts.length)],this.currentArtifact===this.artifacts[0]?this.points+=100:this.currentArtifact===this.artifacts[1]?this.points+=60:this.currentArtifact===this.artifacts[2]?this.points+=50:this.currentArtifact===this.artifacts[3]?this.points+=70:this.currentArtifact===this.artifacts[4]?this.points+=90:this.currentArtifact===this.artifacts[5]&&(this.points+=80),this.refreshStats(),this.currentArtifact.visible=!0,this.currentArtifact.x=t,this.game.time.events.add(Phaser.Timer.SECOND,this.currentArtifactInvisible,this),this.player.loadTexture("player"),this.player.animations.play("walk",3,!0),this.player.body.setSize(this.player.standDimensions.width,this.player.standDimensions.height),this.stopped=!1},currentArtifactInvisible:function(){this.currentArtifact.visible=!1},playerScratch:function(){this.stopped=!1,this.scratches>=6+this.anotherLives?(this.dieSound.play(),this.player.alive=!1,this.orcs.destroy(),this.manticores.destroy(),this.trolls.destroy(),this.chests.destroy(),this.player.loadTexture("player"),this.player.animations.play("walk",30,!0),this.player.body.setSize(this.player.standDimensions.width,this.player.standDimensions.height),this.player.anchor.setTo(.5,1),this.player.scale.x=-1,this.player.body.velocity.x=-500,this.game.camera.unfollow(),this.game.time.events.add(2e3,this.gameOver,this)):(this.player.loadTexture("player"),this.player.animations.play("walk",8,!0),this.player.body.setSize(this.player.standDimensions.width,this.player.standDimensions.height))},generateChests:function(){this.chests=this.game.add.group(),this.chests.enableBody=!0
for(var t,i=this.game.rnd.integerInRange(0,3),e=0;i>e;e++){var s=this.game.rnd.integerInRange(this.game.width,this.game.world.width-this.game.width)
t=this.chests.create(s,this.game.height-136,"chest"),t.body.velocity.x=0}},generateManticores:function(){this.manticores=this.game.add.group(),this.manticores.enableBody=!0
for(var t,i=this.game.rnd.integerInRange(0,2),e=0;i>e;e++){var s=this.game.rnd.integerInRange(this.game.width,this.game.world.width-this.game.width)
t=this.manticores.create(s,this.game.height-200,"manticore"),t.body.velocity.x=this.game.rnd.integerInRange(-70,0),t.body.immovable=!0,t.body.collideWorldBouns=!1}},generateTrolls:function(){this.trolls=this.game.add.group(),this.trolls.enableBody=!0
for(var t,i=this.game.rnd.integerInRange(1,4),e=0;i>e;e++){var s=this.game.rnd.integerInRange(this.game.width,this.game.world.width-this.game.width)
t=this.trolls.create(s,this.game.height-152,"troll"),t.body.velocity.x=this.game.rnd.integerInRange(-40,0),t.body.immovable=!0,t.body.collideWorldBouns=!1}},generateOrcs:function(){this.orcs=this.game.add.group(),this.orcs.enableBody=!0
for(var t,i=this.game.rnd.integerInRange(0,1),e=0;i>e;e++){var s=this.game.rnd.integerInRange(this.game.width,this.game.world.width-this.game.width)
t=this.orcs.create(s,this.game.height-280,"orc"),t.body.velocity.x=this.game.rnd.integerInRange(-80,0),t.body.immovable=!0,t.body.collideWorldBouns=!1}},render:function(){}}
